=== emylyano3/proeza-sah/src/main/resources/gui.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- Definicion de tipos de atributos -->
	<!-- Tipos simples -->
	<xs:simpleType name="colorType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z,0-9]{6}" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="booleanType">
		<xs:restriction base="xs:string">
			<xs:pattern value="true|false" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="orientationType">
		<xs:restriction base="xs:string">
			<xs:pattern value="horizontal|vertical" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="fontStyleType">
		<xs:restriction base="xs:string">
			<xs:pattern value="plain|bold|italic|bold_italic" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="intType">
		<xs:restriction base="xs:positiveInteger" />
	</xs:simpleType>
	<!-- Tipos complejos -->
	<xs:complexType name="sizeType">
		<xs:attribute ref="width" />
		<xs:attribute ref="height" />
	</xs:complexType>
	<xs:complexType name="classType">
		<xs:attribute ref="class" use="required" />
	</xs:complexType>

	<!-- Definicion de tipos de componentes -->
	<!-- Componente Abstracto - Representa a la clase JComponent -->
	<xs:complexType name="uiComponentType">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="max_size" type="sizeType" minOccurs="0" maxOccurs="1" />
			<xs:element name="min_size" type="sizeType" minOccurs="0" maxOccurs="1" />
			<xs:element name="pref_size" type="sizeType" minOccurs="0" maxOccurs="1" />
			<xs:element ref="border" minOccurs="0" maxOccurs="1" />
			<xs:element ref="font" minOccurs="0" maxOccurs="1" />
			<xs:element ref="layout" minOccurs="0" maxOccurs="1" />
			<xs:element ref="mouse_listener" minOccurs="0" maxOccurs="unbounded" />
			<xs:element ref="focus_listener" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
		<xs:attribute ref="name" use="required" />
		<xs:attribute ref="enabled" />
		<xs:attribute ref="visible" />
		<xs:attribute ref="tool_tip" />
		<xs:attribute ref="bgc" />
		<xs:attribute ref="fgc" />
	</xs:complexType>
	<!-- Representa a la clase JLabel -->
	<xs:complexType name="labelType">
		<xs:complexContent>
			<xs:extension base="uiComponentType">
				<xs:attribute ref="text" />
				<xs:attribute ref="icon" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<!-- Representa a la clase JToolBar -->
	<xs:complexType name="toolbarType">
		<xs:complexContent>
			<xs:extension base="uiComponentType">
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="toggle_button" maxOccurs="unbounded" minOccurs="1" />
					<xs:element ref="button" maxOccurs="unbounded" minOccurs="1" />
				</xs:choice>
				<xs:attribute ref="floatable" />
				<xs:attribute ref="rollover" />
				<xs:attribute ref="orientation" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<!-- Representa a la clase JMenuBar -->
	<xs:complexType name="menubarType">
		<xs:complexContent>
			<xs:extension base="uiComponentType">
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="menu_item" minOccurs="0" maxOccurs="unbounded" />
					<xs:element ref="menu" minOccurs="0" maxOccurs="unbounded" />
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<!-- Representa a la clase JTable -->
	<xs:complexType name="tableType">
		<xs:complexContent>
			<xs:extension base="uiComponentType">
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="table_model" minOccurs="0" maxOccurs="unbounded" />
					<xs:element ref="table_header" minOccurs="0" maxOccurs="unbounded" />
					<xs:element ref="cell_renderer" minOccurs="0" maxOccurs="unbounded" />
					<xs:element ref="col_widths" minOccurs="0" maxOccurs="unbounded" />
				</xs:choice>
				<xs:attribute ref="row_height" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<!-- Representa a la clase AbstractButton -->
	<xs:complexType name="buttonType">
		<xs:complexContent>
			<xs:extension base="uiComponentType">
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="action_listener" minOccurs="0" maxOccurs="unbounded" />
				</xs:choice>
				<xs:attribute ref="text" />
				<xs:attribute ref="icon" />
				<xs:attribute ref="selected" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<!-- Representa a la clase JPopupMenu -->
	<xs:complexType name="popupmenuType">
		<xs:complexContent>
			<xs:extension base="uiComponentType">
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="menu_item" minOccurs="0" maxOccurs="unbounded" />
					<xs:element ref="menu" minOccurs="0" maxOccurs="unbounded" />
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<!-- Representa a la clase JMenuItem -->
	<xs:complexType name="menuitemType">
		<xs:complexContent>
			<xs:extension base="buttonType">
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="menu_item" minOccurs="0" maxOccurs="unbounded" />
					<xs:element ref="menu" minOccurs="0" maxOccurs="unbounded" />
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<!-- Representa a la clase JMenu -->
	<xs:complexType name="menuType">
		<xs:complexContent>
			<xs:extension base="menuitemType">
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<!-- Representa a la clase JTextComponent -->
	<xs:complexType name="textComponentType">
		<xs:complexContent>
			<xs:extension base="uiComponentType">
				<xs:sequence>
					<xs:element ref="clipboard" minOccurs="0" maxOccurs="1" />
					<xs:element ref="document_listener" minOccurs="0" maxOccurs="unbounded" />
				</xs:sequence>
				<xs:attribute ref="text" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<!-- Representa a la clase JTextArea -->
	<xs:complexType name="comboType">
		<xs:complexContent>
			<xs:extension base="uiComponentType">
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="action_listener" minOccurs="0" maxOccurs="unbounded" />
					<xs:element ref="data_list" minOccurs="0" maxOccurs="1" />
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<!-- Definicion de atributos -->
	<!-- String -->
	<xs:attribute name="name" type="xs:string" />
	<xs:attribute name="text" type="xs:string" />
	<xs:attribute name="tool_tip" type="xs:string" />
	<xs:attribute name="title" type="xs:string" />
	<xs:attribute name="class" type="xs:string" />
	<xs:attribute name="value" type="xs:string" />
	<xs:attribute name="icon" type="xs:string" />
	<xs:attribute name="col_names" type="xs:string" />
	<xs:attribute name="col_source" type="xs:string" />
	<xs:attribute name="bgc" type="colorType" />
	<xs:attribute name="fgc" type="colorType" />
	<xs:attribute name="selected_bgc" type="xs:string" />
	<xs:attribute name="selected_fgc" type="xs:string" />
	<xs:attribute name="editable_bgc" type="xs:string" />
	<xs:attribute name="editable_fgc" type="xs:string" />
	<xs:attribute name="non_editable_bgc" type="xs:string" />
	<xs:attribute name="non_editable_fgc" type="xs:string" />
	<!-- Otro -->
	<xs:attribute name="style" type="fontStyleType" />
	<xs:attribute name="orientation" type="orientationType" />
	<!-- Booleano -->
	<xs:attribute name="enabled" type="booleanType" />
	<xs:attribute name="visible" type="booleanType" />
	<xs:attribute name="rollover" type="booleanType" />
	<xs:attribute name="floatable" type="booleanType" />
	<xs:attribute name="selected" type="booleanType" />
	<xs:attribute name="first_empty" type="booleanType" />
	<xs:attribute name="sort" type="booleanType" />
	<!-- Entero -->
	<xs:attribute name="size" type="intType" />
	<xs:attribute name="width" type="intType" />
	<xs:attribute name="height" type="intType" />
	<xs:attribute name="row_height" type="intType" />

	<!-- Definicion de atributos complejos -->
	<xs:element name="clipboard" />

	<xs:element name="data_list">
		<xs:complexType>
			<xs:attribute ref="value" use="required" />
			<xs:attribute ref="first_empty" use="required" />
			<xs:attribute ref="sort" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="font">
		<xs:complexType>
			<xs:attribute ref="name" use="required" />
			<xs:attribute ref="style" use="required" />
			<xs:attribute ref="size" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="table_header">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="font" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="table_model">
		<xs:complexType>
			<xs:attribute ref="col_names" use="required" />
			<xs:attribute ref="col_source" use="required" />
			<xs:attribute ref="class" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="table_color">
		<xs:complexType>
			<xs:attribute ref="editable_bgc" use="required" />
			<xs:attribute ref="editable_fgc" use="required" />
			<xs:attribute ref="non_editable_bgc" use="required" />
			<xs:attribute ref="non_editable_fgc" use="required" />
			<xs:attribute ref="selected_bgc" use="required" />
			<xs:attribute ref="selected_fgc" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="cell_renderer">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="font" minOccurs="0" maxOccurs="1" />
				<xs:element ref="table_color" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
			<xs:attribute ref="class" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="col_widths">
		<xs:complexType>
			<xs:attribute ref="value" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="document_listener" type="classType" />
	<xs:element name="mouse_listener" type="classType" />
	<xs:element name="action_listener" type="classType" />
	<xs:element name="focus_listener" type="classType" />
	<xs:element name="layout" type="classType" />
	<xs:element name="border">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="font" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
			<xs:attribute ref="class" use="required" />
			<xs:attribute ref="title" />
		</xs:complexType>
	</xs:element>

	<!-- Definicion de componentes -->
	<xs:element name="binded_combo" type="comboType" />
	<xs:element name="button" type="buttonType" />
	<xs:element name="check_box" type="buttonType" />
	<xs:element name="combo_box" type="comboType" />
	<xs:element name="label" type="labelType" />
	<xs:element name="menu_item" type="menuitemType" />
	<xs:element name="menu" type="menuType" />
	<xs:element name="menu_bar" type="menubarType" />
	<xs:element name="panel" type="uiComponentType" />
	<xs:element name="popup_menu" type="popupmenuType" />
	<xs:element name="scroll_pane" type="uiComponentType" />
	<xs:element name="separator" type="uiComponentType" />
	<xs:element name="table" type="tableType" />
	<xs:element name="text_area" type="textComponentType" />
	<xs:element name="text_field" type="textComponentType" />
	<xs:element name="toggle_button" type="buttonType" />
	<xs:element name="tool_bar" type="toolbarType" />

	<!-- Definicion de grupos de componentes -->
	<xs:element name="labels">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="label" maxOccurs="unbounded" minOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="separators">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="separator" maxOccurs="unbounded" minOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tables">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="table" maxOccurs="unbounded" minOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="text_fields">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="text_field" maxOccurs="unbounded" minOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="text_areas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="text_area" maxOccurs="unbounded" minOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="binded_combos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="binded_combo" maxOccurs="unbounded" minOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="combo_boxes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="combo_box" maxOccurs="unbounded" minOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="panels">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="panel" maxOccurs="unbounded" minOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="popup_menus">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="popup_menu" maxOccurs="unbounded" minOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="scroll_panes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="scroll_pane" maxOccurs="unbounded" minOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="buttons">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="button" maxOccurs="unbounded" minOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="toggle_buttons">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="toggle_button" maxOccurs="unbounded" minOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="check_boxes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="check_box" maxOccurs="unbounded" minOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tool_bars">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tool_bar" maxOccurs="unbounded" minOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="menu_items">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="menu_item" maxOccurs="unbounded" minOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="menus">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="menu" maxOccurs="unbounded" minOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="menu_bars">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="menu_bar" maxOccurs="unbounded" minOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- Definicion de la conformacion del nodo principal que representa a la interfaz -->
	<xs:element name="gui">
		<xs:complexType mixed="true">
			<xs:all>
				<xs:element ref="binded_combos" minOccurs="0" />
				<xs:element ref="buttons" minOccurs="0" />
				<xs:element ref="check_boxes" minOccurs="0" />
				<xs:element ref="combo_boxes" minOccurs="0" />
				<xs:element ref="labels" minOccurs="0" />
				<xs:element ref="menus" minOccurs="0" />
				<xs:element ref="menu_items" minOccurs="0" />
				<xs:element ref="menu_bars" minOccurs="0" />
				<xs:element ref="panels" minOccurs="0" />
				<xs:element ref="popup_menus" minOccurs="0" />
				<xs:element ref="separators" minOccurs="0" />
				<xs:element ref="scroll_panes" minOccurs="0" />
				<xs:element ref="tables" minOccurs="0" />
				<xs:element ref="text_fields" minOccurs="0" />
				<xs:element ref="text_areas" minOccurs="0" />
				<xs:element ref="tool_bars" minOccurs="0" />
				<xs:element ref="toggle_buttons" minOccurs="0" />
			</xs:all>
			<xs:attribute ref="name" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== emylyano3/proeza-sah/src/main/resources/sah-main-window.xml
<?xml version="1.0" encoding="UTF-8"?>
<gui name="sah-main" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="gui.xsd">

	<image_toggle_buttons>
		<image_toggle_button name="ledSwitch" rollover_icon="/images/bulbOff_64x64.png" pressed_icon="/images/bulbOn_64x64.png"
			normal_icon="/images/bulbOff_64x64.png">
			<font name="Arial" style="plain" size="14" />
			<action_listener class="proeza.sah.desktop.listener.light.LightsSwitchListener" />
		</image_toggle_button>
	</image_toggle_buttons>
	<buttons>
		<button name="status" icon="/images/status_64x64.png" >
			<action_listener class="proeza.sah.desktop.listener.light.AskStatusListener" />
		</button>
	</buttons>
	<panels>
		<panel name="main" enabled="true">
			<min_size width="500" height="550" />
			<pref_size width="550" height="550" />
			<border class="javax.swing.border.TitledBorder" title="Panel principal">
				<font name="Arial" style="bold" size="15" />
			</border>
			<font name="Arial" style="bold" size="15" />
			<layout class="org.jdesktop.layout.GroupLayout" />
		</panel>
	</panels>
</gui>
